- Cargo.toml
- src/integer.rs
- src/lib.rs
LMDB allows the use of fixed-width integer keys by passing `INTEGER_KEY` as a flag.
In C, this is a huge footgun:
- You can pass integers of the wrong size.
- You can pass integers to non-integer-key stores, and non-integers to integer-key stores.
- You can use signed or unsigned integers by accident.
- Presumably you can run into endianness or machine-size issues in portability.
Rust allows us to prevent all of these.
This PR uses bincode to encode passed integers, wrapping them in a `Key` struct that implements `AsRef<[u8]>` to pass through. `IntegerStore` is distinct from `Store` because I'd rather have something work than carefully craft more Rust!
Note that we can't do something like `Into<AsRef<[u8]>>` because encoding is failable.
We _could_ effectively implement `AsRef` for …
> Integer keys

- src/env.rs
- src/readwrite.rs
`Store.write()` requires its `&self` argument to be mutable, but it isn't clear why, since `Store` is a "wrapper around an `lmdb::Database`," and it seems like those are intended to be long-lived and used by both read-only and read-write transactions, per [LMDB > Getting Started](http://www.lmdb.tech/doc/starting.html), which states:
> Generally databases should only be opened once, by the first transaction in the process. After the first transaction completes, the database handles can freely be used by all subsequent transactions.
Nor do I see anything about the Store abstraction that suggests that it needs to impose this additional constraint to support a more humane API. Although I'm new to this codebase (and Rust more generally), so I might be missing something!
Presumably it's better …
> don't require store to be mutable to obtain writer for it

- src/env.rs
- src/readwrite.rs
@rnewman: an API question here is whether to be consistent with the abbreviated method name [RwTransaction.del](https://docs.rs/lmdb/0.8.0/lmdb/struct.RwTransaction.html#method.del)—which is itself consistent with the underlying function name [mdb_del](https://docs.rs/lmdb-sys/0.8.0/lmdb_sys/fn.mdb_del.html)—or use the complete word *delete* as the name of the Writer method.
I've opted for the latter, as this is intended to be a humane interface, and humans usually speak in complete words. A minor consideration is that *del* may encourage [horizontal alignment](https://google.github.io/styleguide/javaguide.html#s4.6.3-horizontal-alignment) with consecutive *get* and *put* calls, which is arguably harmful (although also orthogonal and perhaps not something about which this library should …
> implement deletion from store

- src/manager.rs
The Manager equivalent of `Rkv::with_capacity()`. The `Manager::get_or_create_with_capacity()` function head is a very long line, 132 columns, but it follows existing style (and rustfmt would make many more changes besides). I'm happy to wrap it, however.
> enable specifying capacity when getting or creating Rkv from Manager

- src/env.rs
With key-value stores, a common pattern is to read a value from the database for a given key, apply some business logic (potentially transforming the value), and then to write a new value to the database for that key.
When I try that with rkv, using the same Writer to first read and then write the value, I hit two errors that are unexpected:
```
error[E0502]: cannot borrow `writer` as mutable because it is also borrowed as immutable
--> src/env.rs:254:9
|
252 |         let _existing_value = writer.get("foo").expect("read");
|                               ------ immutable borrow occurs here
253 |         // insert business logic here
254 |         writer.put("foo", &Value::I64(1234)).expect("wrote");
|         ^^^^^^ mutable borrow occurs here
255 | …
```
> add test of canonical read before write on same Writer

- Cargo.toml
- src/lib.rs
- src/manager.rs
- tests/manager.rs
@rnewman `Manager::new` would have to be *pub* in order for a consumer to use it to create a Manager instance that manages database handles for them. But perhaps you have a different plan for how consumers should use Manager?
I suppose it somewhat begs the question to enable consumers to instantiate them directly, since a consumer can then evade the constraint that Manager imposes by instantiating it multiple times. One alternative would be to create a Manager singleton via a lazy static, i.e. something like:
```rust
#[macro_use]
extern crate lazy_static;
lazy_static! {
#[derive(Debug)]
static ref MANAGER: Manager = {
Manager::new()
};
}
```
Then keep `Manager::new()` private to force consumers to get or create Rkv instances via the singleton.
> make Manager consumable

- Cargo.toml
- src/env.rs
- src/value.rs
Here's an implementation of Value::Blob along with tests of round-tripping both a [u8] and a [u16] that we convert to [u8] beforehand and convert back afterward. (Arguably the latter is more a test of the conversion functions than rkv itself, but it's useful documentation for developers who want to use rkv to store similar data.)
@fluffyemily Perhaps you can review this one?
> implement Value::Blob type (fixes #20)

- src/env.rs
- src/readwrite.rs
This implements read-only iteration of `(key, value)` tuples from the start of the store or from a specified key, fixing #23 and providing a useful, humane subset of the functionality provided by LMDB cursors, which are abstracted away by this interface (one requests an _Iter_ directly from a _Reader_ without indirecting through a _Cursor_). Keys are `&[u8]`, while Values are _Value_ instances.
The _Reader.iter()_ and _Reader.iter_from()_ methods are analogous to the same-named methods of LMDB's [RoCursor](https://docs.rs/lmdb/0.8.0/lmdb/struct.RoCursor.html). An alternate interface would be a single _Reader.iter()_ method that accepts an _Option<AsRef<[u8]>_, which can be `None` (to iterate from the start of the store) or `Some(AsRef<[u8])` to start from that key. It wasn't clear which …
> implement iteration from start of store or specified key (fixes #23)

- Cargo.toml
We should publish a new release, as we've landed several features recently, including the Manager, iteration, and Value::Blob, the latter of which deserves a version bump per @rnewman's comment in #20.
> update version for release to crates.io

- .appveyor.yml
This enables CI for windows on AppVeyor, which would require us to set up some stuff on AppVeyor.
Already tried it with my fork, the code appears to be broken on Windows due to the "UNC" path issue, will fix that in another follow up pr.
r? @mykmelez
> add appveyor for CI on windows

- Cargo.toml
- src/lib.rs
- src/manager.rs
Workaround the UNC path on Windows, all the tests passed in the current stable toolchain "stable-x86_64-pc-windows-msvc"
Note that:
* It can't handle the paths longer than MAX_PATH
* It can't handle the paths with the non-utf8 characters
@mykmelez
> workaround unc path on windows

- .rustfmt.toml
- .travis.yml
- README.md
- examples/iterator.rs
- examples/simple-store.rs
- src/env.rs
- src/error.rs
- src/integer.rs
- src/lib.rs
- src/manager.rs
- src/readwrite.rs
- src/value.rs
- tests/manager.rs
This replaces PR #32 in order to avoid those excessive merge conflicts. Also this adds various rustfmt configuration items based on the code review. Lastly, rustfmt check is enabled in TravisCi.
r? @mykmelez Could you take another look? You may notice there are a few long lines in this PR, since we've relaxed the `max_length` up to 120 characters, rustfmt decided to join some short lines to a a one-liner :). We can further tweak it around until we feel they're reasonable enough to get started.
> enable rustfmt

- README.md
- examples/simple-store.rs
- src/lib.rs
This branch adds documentation for the project itself (via Markdown in README.md) as well as the Rust crate that it produces (as embedded comments in lib.rs), with the goal being to cleanly distinguish between those two kinds of docs.  The only overlap between the two is the one-line description ("a simple, humane, typed Rust interface to LMDB"), which I've made consistent between the README, the comments, and the "description" field of the GitHub repo page.
For crate docs, I took inspiration from the [rand](https://docs.rs/rand/0.5.1/rand/), [lazy_static](https://docs.rs/lazy_static/1.0.1/lazy_static/), and [serde](https://docs.serde.rs/serde/) docs while treating [libc](https://docs.rs/libc/0.2.42/libc/) and [winapi](https://docs.rs/winapi/0.3.5/winapi/) as counter-examples.  The usage …
> document project and API

- .travis.yml
https://github.com/rust-lang/rust/issues/51699 has broken the nightly Rust toolchain. Our Travis configuration allows failures when building with that toolchain, but we use nightly rustfmt when building with all toolchains, so the bustage affects our stable and beta builds too.
To work around the problem, this branch uses a specific rustfmt nightly rather than the latest one. (We might want to keep doing this even after the bustage is fixed, to avoid such bustage in the future.)
> use specific rustfmt nightly

- Cargo.toml
- src/lib.rs
@ncalexan After publishing a new version of rkv this morning, I noticed some issues with the crates.io listing and the docs you reviewed yesterday. Here's a set of fixes for them. I also added keywords and a category, and I updated the repo URL.
> fix listing/docs issues

- src/env.rs
This implements an API that opens a rkv store by a read transaction to avoid the deadlocks, see #59 for more details.
r? @mykmelez
> add an api to open a store with read transaction

- examples/iterator.rs
- examples/simple-store.rs
- src/env.rs
- src/integer.rs
- src/lib.rs
- src/readwrite.rs
This is another try to fix #46 based on the discussion in #46.
This patch consists of following parts in 3 commits:
1. move `Reader&Writer` from `Store` to `Rkv`, also remove `get` function from `Store`
2. update all the examples
3. apply similar refactoring to integer store, note that this module appears to be a WIP, it needs some followup patches to support functionalities such as iterators
r? @mykmelez
> Refactor to support multi-store

- src/env.rs
- src/readwrite.rs
@ncalexan Per @rnewman's comment https://github.com/mozilla/rkv/pull/28#issuecomment-395448738, Store can be Copy, and access to it doesn't need to be synchronized, as described by #29. So this branch derives Copy for Store and tests access to it by multiple threads.
> derive Copy for Store (fix #29)

- README.md
The README currently suggests that `cargo test --tests` will run both unit/integration tests and example binaries. That's incorrect, as it'll only run the former. And it skips doc tests.
To run unit, integration, and doc tests, we need to run `cargo test` (no flag). And to run the example binaries, we need to use the run-all-examples.sh shell script, as there's no cargo command that will run all those (`cargo run --example [name]` runs only the specified test, and `cargo test -examples` runs only unit tests within the example binaries).
> correct instructions for running tests and examples

- Cargo.toml
- src/env.rs
Per #70, we should switch from the crates.io package to the [mozilla/lmdb-rs](https://github.com/mozilla/lmdb-rs) fork of the lmdb crate, where we've taken fixes for rkv.
I'd rather not publish [mozilla/lmdb-rs](https://github.com/mozilla/lmdb-rs) to a new crates.io package, which'd require a different (but presumably similar) name, sow confusion about the differences between the two crates, and potentially complicate unforking in the future.
Instead, I'd like to point rkv's lmdb dependency to [mozilla/lmdb-rs](https://github.com/mozilla/lmdb-rs) via its Cargo.toml file's [dependencies] section, which is a paved cow path, f.e. in https://searchfox.org/mozilla-central/source/gfx/wrench/Cargo.toml, where Gecko does that for yaml-rust and osmesa-src.
Another option would be to override rkv's …
> switch lmdb-rs dependency to mozilla/lmdb-rs fork (fix #70)

- Cargo.toml
For the (backward-compatible) change to the lmdb-rkv crate dependency.
> increment patch version to 0.4.1

- src/env.rs
Per the comment from @shivawu in #34 that there should be a way to set an environment's map size, here are tests that demonstrate how to do that.
NB: We should file upstream bugs/PRs in the LMDB crate and C library to fix the code or docs (probably the latter) to agree about the default map size for an LMDB environment.
> test exceeding and increasing the map size

- Cargo.toml
- src/lib.rs
- src/value.rs
There's this comment on the OwnedValue implementation:
> // TODO: implement conversion between the two types of `Value` wrapper.
> // This might be unnecessary: we'll probably jump straight to primitives.
However, I've identified a use case: in Gecko, structs that implement an XPCOM interface may want to store a `Value`, but they can't hold a reference, because the XPCOM Rust binding doesn't support that; so they would need to store an `OwnedValue` instead (or generalize over the primitive type and make their consumers convert the reference types to owned types).
This branch implements the `Value` to `OwnedValue` conversion for storage in XPCOM structs (and any other unknown unknown use cases out there).
It also upgrades the uuid dependency from 0.6 to 0.7, which isn't strictly necessary …
> implement conversion from Value to OwnedValue and expose OwnedValue

- Cargo.toml
This release includes a dependency update from uuid version 0.6 to 0.7, which is a breaking change, since we exposed uuid 0.6's `UuidBytes` type, which has been replaced with the `Bytes` type in uuid 0.7.
Thus I'm bumping the rkv version from 0.5.1 to 0.6.0 (rather than 0.5.2, which is what it would have been otherwise).
> update version to 0.6.0

- examples/iterator.rs
- examples/simple-store.rs
- src/env.rs
- src/integer.rs
- src/lib.rs
- src/readwrite.rs
- src/value.rs
This attempts to fix #87 with following changes:
* Re-define the `rkv::Store` and `rkv::IntegerStore` via the newtype trick
* Change all the Store related APIs from passed-by-reference to be passed-by-value
As mentioned in #87, `rkv::Store` is essentially a wrapper of `lmdb::Database`, which in turn is a plain unsigned integer. Therefore it bears the Copy semantics. If we'd like to stick with the conventions in both LMDB and lmdb-rs, passing it as a value should be preferred here.
Another benefit is that we can also simplify the API signatures with the help of lifetime elision as the life time of Store reference is no longer needed.
The downside is, obviously, it breaks the backward compatibility.
@mykmelez Would like to hear your thoughts on this.
> Replace all the passed-by-reference with passed-by-value for Store

- Cargo.toml
43a8731ff86f7d3110ec492e9ddd6031a655d8d8 converts Store to a newtype and passes it by value, which is a breaking change to the public API.
> update minor version to 0.7.0 for breaking change

- .travis.yml
- src/env.rs
- src/integer.rs
- src/value.rs
We've let a few `cargo fmt` nits creep into the codebase, according to the latest nightly build of Rust. Here are the fixes.
This branch also changes back to using the latest nightly build of Rust to format the code, rather than a fixed/pinned build of nightly.
(We'd previously pinned the build because of Rust nightly build bustage, which is a risk when going back to using the latest nightly. Let's see how it goes and re-pin a build if it breaks too often.)
> fix 'cargo fmt' nits; use latest nightly for 'cargo fmt'

- Cargo.toml
- src/integer.rs
- tests/integer-store.rs
@ncloudioj This just tests that we can generalize across integer types with generic type parameters. It contains only test changes, no functional changes. I created it to help think through the changes we're contemplating in #97, but it seems worth landing as well, to document (and verify) that this works.
Let me know what you think!
> test consumer-specified integer key variants

- examples/iterator.rs
- examples/simple-store.rs
@rrichardson While reviewing #101, I realized that we can remove the `use rkv` and `use tempfile` declarations in examples/, as they're redundant with later declarations that import specific symbols from those crates.
Also, the `use self::rkv::{ … }` declaration happens to work because of the preceding `use rkv` declaration, but `self::` is intended to reference local modules/items, and rkv is actually an external crate in this case (from the perspective of the example, which demonstrates how an external consumer would use rkv).
So this followup branch removes the `use rkv` and `use tempfile` declarations and changes `use self::rkv::{ … }` to `use rkv::{ … }`.
Does this seem reasonable?
> remove unnecessary use declarations, self:: reference

- Cargo.toml
Depending on rkv in a crate that also depends on lazy_static version 1.0.1 can cause the problem described in https://users.rust-lang.org/t/2018-edition-macro-ergonomics/18790 if the consumer causes rkv to also use lazy_static version 1.0.1. We should thus require that rkv use at least lazy_static 1.0.2.
> require lazy_static version 1.0.2

- examples/iterator.rs
- examples/simple-store.rs
- src/env.rs
- src/store/integer.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
- tests/integer-store.rs
- tests/multi-integer-store.rs
Fixes the *Store put/del functions that took &mut self.  Changes everything to &self and removes the warnings from all code that consumes those methods.
> remove mut from the *store mutation functions as it is not needed

- .travis.yml
- examples/iterator.rs
- examples/simple-store.rs
- src/env.rs
- src/store/integer.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
- src/value.rs
This closes #68.
With this change, CI would fail if Clippy sees any warning in the patch, picky...picky ;)
Also silenced a few Clippy warnings (`passing by value instead of ref` and `naming convention`) in this patch, assuming that we do want to keep those behaviors for now.
> integrate clippy into CI

- src/lib.rs
- src/store.rs
- src/store/multi.rs
- src/store/single.rs
This fixes a couple of the nits noted in #101. It also fixes the crate-level documentation in src/lib.rs, which contains some outdated references to documentation pages for the _Store_ and _IntegerStore_ types.
> fix nits and docs

- Cargo.toml
Updates lmdb-rkv dependency to latest stable version 0.11.1 (LMDB 0.9.23). Although this wasn't a breaking change (hence the patch version increment from 0.11.0 to 0.11.1), I think we do want to ensure that rkv consumers get the update to the latest stable LMDB version, which is why I've specified the patch version of the lmdb-rkv dependency.
This also updates rkv minor version to 0.9.0 in preparation for publishing a new version with recent breaking changes. I reviewed the three commits since 0.8.0 (a9f84809b43d3179d32951c652f205d7f8d4cc89, 9c8160f71da358e32f7a3e250049e8ff98a67d0e, 7390e6ff5d91b23b166b5c1e089923209c6f1b05), and they're almost entirely backward-compatible, as the changes are almost entirely additive.
But the change from `&self` to `self` for the first parameter of some …
> update lmdb-rkv dependency and rkv minor version

- src/env.rs
- src/lib.rs
@ncloudioj I noticed some more outdated information in the crate docs. This branch corrects it.
Part of the problem is that the docs include an embedded code sample that itself contains embedded comments, and while the code sample itself is tested, the comments embedded inside it aren't, so it's possible for the information in them to become out-of-date.
In addition to updating those comments, I removed method names from them, as those seem like the parts of the doc that are most likely to become out-of-date. I left in data types, however, and added commentary where it seemed appropriate. I also added a bit more code to demonstrate the interaction between an active writer and a reader.
Finally, I updated the description of the E0382 error message you get when you try to reuse a committed …
> correct crate docs

- examples/iterator.rs
- examples/simple-store.rs
- src/env.rs
- src/lib.rs
- src/readwrite.rs
- src/store.rs
- src/store/integer.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
- tests/integer-store.rs
- tests/multi-integer-store.rs
@ncloudioj @rrichardson This branch re-wraps LMDB transactions in a Reader/Writer abstraction to fix #115.
The names aren't important, and I'm happy to use something else (even the same names as LMDB). I just want to achieve consistency in the return values of rkv methods, so they don't return sometimes `Result<_, StoreError>` and other times `Result<_, lmdb::Error>`.
In the process, I also added testing of `MultiStore.get_first()` and `MultiStore.delete_all()` to confirm that they work as expected.
Let me know what you think.
> wrap lmdb-rs transactions in rkv abstraction

- Cargo.toml
Update the patch version for rkv to 0.9.1 and its lmdb-rkv dependency version to 0.11.2 in preparation for publishing rkv 0.9.1.
> update patch version to 0.9.1 for lmdb-rkv 0.11.2

- src/value.rs
This has been sitting in my local clone for a while, and I don't remember why I never requested a pull for it. It enables some downstream refactoring in the kvstore consumer (which currently implements its own _OwnedValue_ type): https://github.com/mykmelez/gecko/compare/central-update-rkv...use-rkv-owned-value
@rnewman I'm curious if it was intentional to make `Value::F64` store an `OrderedFloat<f64>` but `OwnedValue::F64` store a primitive `f64`. An earlier version of this branch made `OwnedValue::F64` also store an `OrderedFloat<f64>`, so that it could derive `Eq`.
I've undone that change in the current version of this branch, as it didn't turn out to be necessary to support the downstream use case; but I'm curious for your thoughts on the relative merits of retaining the current type …
> derive Clone for OwnedValue

- .travis.yml
- src/value.rs
Over in https://phabricator.services.mozilla.com/D19436#inline-106713, @mystor wondered why rkv doesn't provide a conversion from `OwnedValue` to `Value`, which is indeed a missing piece in rkv's API that requires downstream consumers like kvstore to implement the conversion themselves.
Here's an implementation that enables downstream consumers like kvstore to avoid implementing it themselves. Along the way, I removed unnecessary `ref` annotations now that rkv specifies `edition = "2018"` and thus [infers the binding mode for match bindings](https://rust-lang-nursery.github.io/edition-guide/rust-2018/ownership-and-lifetimes/default-match-bindings.html).
> implement From<OwnedValue> for Value

- examples/simple-store.rs
- src/env.rs
- src/lib.rs
- src/readwrite.rs
- src/store/integer.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
This fixes the "clear" part of #126.
With this addition, we can then implement the bulk insert&delete for kvstore.
> Implement clear for stores

- src/value.rs
This can be used to inspect the size of `rkv::Value`, which in turn could be useful for map resizing.
> Add serialized_size to Value enum

- Cargo.toml
Once this is merged, I'll publish the crate to crates.io, and that'll fix #140.
> update version for 0.9.5 release (fixes #140)

- src/env.rs
@victorporof This was my attempt to reproduce the mdb_cursor_put crash via a too-long key. Long story short, I didn't reproduce it; LMDB just returns an error. But I wonder if some different key size might do so, or if there's something else about the way that LMDB is compiled into Firefox that causes it to crash instead of returning an error.
(Regardless, I guess it's useful to have this test, although ideally rkv would prevent its consumers from using an overlong key to begin with.)
> test exceeding LMDB's key size limit

- src/manager.rs
Because Manager stores Rkv instances as Arc<RwLock<Rkv>>, and RwLock has interior mutability, it's possible to replace a managed Rkv instance, resulting in surprising behavior when retrieving instances from the Manager.
This branch just demonstrates the surprising behavior of Manager when one of its mapped Rkv instances is replaced by a new instance.
> test that one can mutate managed Rkv instances in surprising ways

- Cargo.toml
> Use relaxed dependency versions (pre 0.10) for better build compat with m-c

- Cargo.toml
- examples/iterator.rs
- examples/simple-store.rs
- src/backend.rs
- src/backend/impl_lmdb/database.rs
- src/backend/impl_safe.rs
- src/backend/impl_safe/database.rs
- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/error.rs
- src/backend/impl_safe/transaction.rs
- src/backend/traits.rs
- src/env.rs
- src/store/integer.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
- tests/test_txn.rs
In https://github.com/mozilla/rkv/pull/158#issuecomment-548693019 I've explained why dropping the requirement for `Copy` and `Eq` traits was necessary for database instances.
Turns out I lied. We can use arena allocation and opaque keys as database handles. Doing so allows us to preserve the copy and equality trait requirements on "databases" (as users see them).
This patch does the following:
1. Re-enables copy and equality trait requirements on databases.
2. Returns database handles instead of database instances to consumers, in situations such as calling `open_db` or `create_db` on environments, or when dealing with transactions.
3. Derives copy and equality traits on single/multi database helpers.
This ends up simplifying things quite a lot, removes an entire class of errors, removes …
> Safe mode arena allocation for databases

- Cargo.toml
- src/backend/impl_safe/database.rs
We're using `std::collections::HashMap`'s `Entry` API to store keys/values in our safe mode database implementation. This is more ergonomic than using an imperative API, and more performant in the ideal case.
However, the real world isn't ideal, and we end up needlessly reallocating keys and values when interacting with the database. For example, using the `Entry` API to insert a key/value pair into the database results in a copy of the key when the value was already added. Similarly (in an even worse case scenario), deleting all values matching a key copies the key, and attempts clearing an already empty `BTreeSet` representing our values.
The `Entry` API is long known for having poor performance in those situations, with [many …
> Prevent needless key/value copies in database methods

- Cargo.toml
- src/backend/impl_safe/cursor.rs
- src/backend/impl_safe/database.rs
- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/error.rs
- src/backend/impl_safe/transaction.rs
- src/env.rs
I've identified 3 additional situations where our safe mode backend implementation doesn't match LMDB's behavior, fixed in the following 3 individual commits.
> LMDB behavior parity

- src/value.rs
> Fix clippy `inefficient_to_string` warnings on string values

- src/backend/impl_lmdb/cursor.rs
- src/backend/impl_lmdb/iter.rs
- src/backend/impl_safe/cursor.rs
- src/backend/traits.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
LMDB semantics dictate that a cursor must be valid for calls to `mdb_cursor_get`. In case of the rust wrappers, this means that the `lmdb::RoCursor`/`lmdb::RwCursor` must be valid the entire lifetime of an `lmdb::Iter`. In other words, cursors must not be dropped while an iterator built from it is alive. Unfortunately, the LMDB crate API does not express this through the type system at all, so we must enforce it somehow.
Before this PR, this worked because dead code wasn't eliminated. The `Iter` types for single/multi database wrappers owned a `C` generic type implementing `BackendRoCursor`, even though they didn't have to.
In case of a safe mode backend, this isn't required, and eliminating the dead code doesn't result in any SIGSEGV. …
> Fix cursor/iterator lifetime coupling which can result in referencing invalid memory when eliminating dead code

- src/backend/impl_lmdb/cursor.rs
- src/backend/impl_safe/cursor.rs
- src/backend/traits.rs
- src/store/integermulti.rs
- src/store/multi.rs
- src/store/single.rs
- tests/test_txn.rs
We're reallocating keys when creating 'from' and 'dup_of' iterators. In practice, this isn't necessary as long as we require keys to live at least as long as the iterators themselves, which is always going to be true.
This PR adds a lifetime constraint for those situations, removing the need for a reallocation.
> Don't allocate when creating 'from' and 'dup_of' iterators

- src/backend/impl_safe/cursor.rs
- src/backend/impl_safe/snapshot.rs
When generating iterators for multi databases, the (key, value**s**) iterator generated by a snapshot is first flattened into (key, value) iterator; then, this iterator is transformed with `skip_while` and `filter` adaptors.
This approach can be less performant in a situation where a key can contain multiple values. In these situations, these adaptors do extra work because the flattening happens beforehand. Ideally, flattening should happen afterwards, which this PR implements.
> Delay short-circuiting `skip_while` and `filter` adaptors for better perforamnce in case of multi databases

- src/backend/impl_safe/environment.rs
- src/env.rs
No reason to have this different between `open` and `create`, since a `create` also implies an `open.`
> Opening should fail when read transactions exist for `open` and `create` operations

- src/backend.rs
- src/backend/impl_safe.rs
- src/backend/impl_safe/database.rs
- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/transaction.rs
When updating the crate documentation, I noticed that our exports can be confusing when trying to understand how backends work. Ideally, they should be symmetric in terms of exports.
This PR makes it so.
> Make backend-related documentation easier to understand

- src/backend/impl_lmdb/error.rs
- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/error.rs
- src/env.rs
- src/error.rs
When updating kvstore to use RKV in safe mode [bug 1597898](https://bugzilla.mozilla.org/show_bug.cgi?id=1597898), I noticed that more LMDB-related errors were used at the top-level.
Ideally, common backend errors should be exposed as top-level store errors. This allows consumers not have to worry about which backend they're using when handling various errors in general.
For example, In case of CRLite, this was just KeyValuePairNotFound. It's better to have this a top-level store error, because otherwise consumers would have to guard for both the LMDB and SafeMode variants of this error. And if they switch to a third backend in the future, they'd have to remember to add a third guard everywhere. A similar story is in case of kvstore.
Obviously, we shouldn't do this for clearly …
> Error ergonomics

- Cargo.toml
- src/backend/impl_lmdb/environment.rs
- src/backend/impl_lmdb/error.rs
- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/error.rs
- src/backend/traits.rs
- src/env.rs
- src/error.rs
- src/helpers.rs
- src/lib.rs
- src/manager.rs
- src/migrator.rs
- tests/env-lmdb.rs
- tests/env-migration.rs
- tests/env-safe.rs
This makes it so that users don't need to manually open an old environment to migrate. Really they just want open their environment normally, and optionally populate it with with whatever was there to begin with.
This PR makes migration a one liner.
> Make migration easier for consumers

- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/transaction.rs
- src/migrator.rs
- tests/env-migration.rs
This PR does 2 things:
1. Fixes bug https://bugzilla.mozilla.org/show_bug.cgi?id=1663856
This is a fun one. If old migrated data isn't deleted (e.g. when there's multiple environments open at the same path and deleting the files would be invalid while another environment is still open), it's possible that databases with new a different storage drivers (e.g. safe-mode) continue to be created and end up populated at runtime. Next time migration is attempted, migration doesn't fail silently anymore (since the destination is not empty). See [comment 5](https://bugzilla.mozilla.org/show_bug.cgi?id=1663856#c5)).
I've added some tests for this and now handling the `DestinationNotEmpty` situations. In every situation, the consumer code that's using this helper:
- Is not concerned by throwing away …
> Migration updates

- src/backend/impl_lmdb/environment.rs
- src/backend/impl_safe/environment.rs
- src/backend/traits.rs
- src/env.rs
- src/error.rs
- src/lib.rs
- src/manager.rs
- src/migrator.rs
- src/store.rs
- tests/manager.rs
Right now, if database files are corrupted, opening an environment at that path will fail with `FileInvalid` (every time with SafeMode, and only _sometimes_ with LMDB unless corruption is extreme in which case we just crash).
The only way for users to deal this right now is to manually delete the files before attempting to reopen –– which is also incorrect if there's lingering environments. This is also very inelegant when dealing with multiple possible backends, where users might not know exactly which files to delete.
I've recently added `try_close_and_delete` to Managers, and `close_and_delete` to Environments, which delete the files on close. This is only useful though if you've already successfully opened an environment at least once with the former, or already have direct ownership …
> Add a way to discard corrupted databases on load

- Cargo.toml
I am trying to build Glean using minimal versions (`cargo +nightly update -Z minimal-versions`) and this is another dependency that breaks.
ordered-float dropped the `unreachable` dependency in 1.0.1, which makes it work again.
> Update dependencies to minimal supported versions

- Cargo.toml
- README.md
- src/backend/impl_lmdb/arch_migrator_error.rs
- src/error.rs
- src/lib.rs
[`failure`](https://github.com/rust-lang-nursery/failure) has been deprecated in favor of `thiserror`. This PR replaces it.
> Replace failure with thiserror

- Cargo.toml
Also contains the fixes for https://github.com/advisories/GHSA-566x-hhrf-qf8m
> Upgrade to latest ordered-float

- Cargo.toml
Not sure why this was restricted, but unless we losen this dependency range we cannot get it into m-c.
> Allow bitflags 1.2+

- src/backend/impl_safe/environment.rs
This ensures that _some_ data is still around in the case that the write gets interrupted early.
This currently can cause data loss with the whole database getting wiped.
> Write database to temp file first, then atomically move it

- Cargo.toml
- src/backend/impl_lmdb/arch_migrator.rs
- src/backend/impl_safe/environment.rs
- src/backend/impl_safe/flags.rs
This should fix the Nightly failure in #235 (which is not a blocker).
Followed the migration guide of https://github.com/bitflags/bitflags/releases/tag/2.0.0. `PartialEq, Eq, Debug, Clone, Copy` is to match the BackendFlags requirement:
https://github.com/mozilla/rkv/blob/55a5a4dc94e84d77e25637dc68dc8222c72db403/src/backend/traits.rs#L25
> Upgrade `bitflags` to from 1.2 to 2.4

- src/backend/common.rs
- src/backend/impl_lmdb/environment.rs
- src/backend/impl_safe/environment.rs
- src/backend/traits.rs
- tests/manager.rs
Fixes #234
This is a breaking change because of the now-changed public API
> Introduce a recovery strategy as a replacement for set_discard_if_corrupted
