src/readwrite.rs
Comment-only change that explains why Reader.iter_start() calls Cursor.iter() instead of Cursor.iter_start().
=> explain call to Cursor.iter() in Reader.iter_start()

examples/README.md, examples/simple-store.rs
Taking the first crack at adding some examples to this project. This intends to showcase the basic usage of rkv to give people some basic idea, so it doesn't cover features such as cursors, dup_sort store etc. Assuming that we can demostrate more advanced usages in the following examples. What do you think? @mykmelez
=> add an example to demo the basic usage of rkv

examples/README.md, examples/iterator.rs
=> add an example for iterators

.travis.yml, run-all-examples.sh
This closes #36 (on Travis only) ;)
r? @mykmelez
=> run examples in travis

examples/simple-store.rs, src/lib.rs
=> Fix Bug #54 - Update the example about reading the uncommited writes

examples/iterator.rs, examples/simple-store.rs, src/env.rs, src/integer.rs, src/lib.rs
=> Rename create_or_open to open_or_create

src/env.rs
A followup of #61 
r? @mykmelez
=> add a test to cover the bad_rslot error

src/env.rs
@ncloudioj This fixes the other inconsistency we noticed in method signatures by reordering the params of *Rkv::from_env()*, so its first parameter is the same—_path_—as the other two static Rkv constructors, _Rkv::new()_ and _Rkv::with_capacity()_.
I also added explicit tests for *Rkv::from_env()* and *Rkv::with_capacity()*. Both of those are implicitly tested by the tests for *Rkv::new()*, but I prefer to also have explicit tests for them, which can be more extensive; like the test for *Rkv::with_capacity()*, which confirms that trying to open too many databases causes a panic.
Speaking of which, I also filed https://github.com/mozilla/lmdb-rs/issues/6 to suggest that lmdb-rs return Result<Error> instead of panicking in that case (and others).
Finally, I replaced one call to …
=> order path param consistently in Rkv constructors (fix #45)

Cargo.toml
Increment patch version to publish change from new-ordered-float to ordered-float.
=> increment patch version

Cargo.toml
@ncloudioj and I have made significant contributions to the project over the last few months. We've both exceeded the commit count of the original author! So this adds us to the list of authors. (Unsure of convention, but there's clearly intent for the list to include multiple authors, and it seems reasonable for it to reflect the major contributors.)
=> update authors list to reflect significant contributions

src/lib.rs
Oops, I missed this one in my last PR.
@mykmelez r?
=> Update crate document

src/env.rs
This was a test I wrote to demonstrate workarounds for #90. After thinking about it, I concluded that it's worth landing as a test, to ensure that these workarounds continue to work, and to demonstrate them for folks using tests as documentation. So I've rebased it against master, simplified it where possible, and added some additional commentary.
=> test using a value as a key

Cargo.toml
@ncloudioj This includes #127.
=> update patch version for 0.9.4 release

src/lib.rs
Everything is in the title, my approach is right or there is another one that i have not seen ?
=> Export  'Readable' trait to allow user making generic method that take '&Readable' as parameter instead of '&Read' or '&Write'

Cargo.toml, src/lib.rs, tests/test_txn.rs
This is an integration test demonstrating the use of helper functions within transactions.
=> added tests for Readable txns

.appveyor.yml, .travis.yml
=> Various CI updates

Cargo.toml
=> Add CI badges to readme

src/backend/impl_lmdb/error.rs, src/backend/impl_safe/error.rs, src/env.rs, src/error.rs
=> Ensure backends interop well when opened from the same directory

src/env.rs
=> Add tests verifying that deletion also fails with a top-level store error

src/lib.rs, src/value.rs
=> Remove dead code

Cargo.toml
=> Bump version to 0.11.0

src/backend/impl_safe/environment.rs, tests/env-lmdb.rs, tests/env-safe.rs
=> Fix inconsistent max_dbs behavior between backends

src/backend/impl_lmdb/environment.rs, src/backend/impl_lmdb/error.rs, src/backend/impl_safe/environment.rs, src/backend/traits.rs, src/env.rs, tests/env-lmdb.rs, tests/env-safe.rs
=> Graciously handle backends with no need for resizing, instead of throwing unimplemented!()

src/backend/impl_lmdb/environment.rs, src/backend/impl_lmdb/error.rs, src/backend/impl_lmdb/iter.rs, src/backend/impl_lmdb/transaction.rs, src/backend/impl_safe/environment.rs, src/backend/impl_safe/error.rs, src/backend/traits.rs, src/env.rs, tests/env-lmdb.rs, tests/env-safe.rs
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1653555
=> Allow creating dirs if they don't exist

src/migrator.rs, tests/env-migration.rs
Really there's not much that can be done in this situation. The "easy mode" auto migration should handle this automatically, similarly to how other IoError and UnsuitableEnvironmentPath errors are ignored. The non-auto migration is still available for manual/complex handling of such problems.
=> Ignore file invalid errors when migrating

.github/workflows/ci.yml, Cargo.toml
Should fix the build issue in #235. Matches the MSRV in Firefox: https://firefox-source-docs.mozilla.org/writing-rust-code/update-policy.html
=> Bump MSRV to Rust 1.66.0
